### ISSUE TITLE
.bin convert to mp4

### ISSUE THREAD

**Issue by tjinjin95** [Telecommunication-Telemedia-Assessment/V-BMS360#1]
Hi, I have generate a myvideo.bin file by using your code, but I cant convert this .bin file to .mp4 file, would you show me the method ? @slhck @stg7 @jantoskowronek @sfremerey @plebreton

**Comment by plebreton** [comment]
Hi,

There is no easy way to convert the .bin file to .mp4 
The .bin file contains the pixel values frame by frame, in float32, rasterscan order, with width/height identical to the source (except if you use some scaling function).

The binary is however able to generate a compressed .mp4 file by running:
./salient-video.exe -i input_video.mp4 -o output_saliency.mp4

Similarly, the image model can also generate compressed image:
./salient-image.exe -i input_image.png -o output_saliency.png


If you want to get a .mp4 from the .bin file you already processed without re-running everything, I think the easiest way would be to write a script to read the .bin file, scale the float numbers to unsigned char 8 bit, and then you could generate a YUV 420p file, that  you could encode using ffmpeg or so. 

However, if you have the time, I would suggest to just re-run the model and ask a .mp4 output by using an output file with the .mp4 extension.
